# Generated by Django 4.2.11 on 2024-05-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0002_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукти'},
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Знижка в відсотках'),
        ),
    ]
